
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-mongodb
  labels:
    oda.tmforum.org/componentName: {{.Release.Name}}-{{.Values.component.type}}
    app: {{.Release.Name}}-mongodb
spec:
  ports:
  - port: 27017
    targetPort: {{.Release.Name}}-mongodb
    name: {{.Release.Name}}-mongodb
  type: NodePort
  selector:
    app: {{.Release.Name}}-mongodb

